name: trcas_catholic
description: A new Flutter project.
publish_to: "none"
version: 2.1.61+1

environment:
  sdk: ^3.10.0

dependencies:
  # add_2_calendar: ^2.2.3
  badges: ^3.1.1
  butter: ^2.2.3

  cloud_firestore: ^5.4.0    # Uses Firebase iOS SDK 11+
  cloud_functions: ^5.1.0    # Uses Firebase iOS SDK 11+
  firebase_analytics: ^11.3.0  # Uses Firebase iOS SDK 11+
  firebase_auth: ^5.3.0      # Uses Firebase iOS SDK 11+
  firebase_core: ^3.6.0      # Uses Firebase iOS SDK 11+
  firebase_crashlytics: ^4.1.0  # Uses Firebase iOS SDK 11+
  firebase_messaging: ^15.1.0   # Uses Firebase iOS SDK 11+
  
  collection: ^1.17.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+1
  dotted_line: ^3.1.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  
  # UPDATED: flutter_html to stable version compatible with Flutter 3.35.2
  flutter_html: ^3.0.0-beta.2  # Updated from 3.0.0-alpha.6 to latest beta
  
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^17.2.3  # Updated for Flutter 3.35.2 compatibility
  flutter_native_splash: ^2.4.1  # Updated for Flutter 3.35.2 compatibility
  flutter_staggered_grid_view: ^0.7.0  # Updated for Flutter 3.35.2 compatibility
  flutter_vector_icons: ^2.0.0
  hexcolor: ^3.0.1
  html: ^0.15.4
  http: ^1.2.2 
  intl: ^0.19.0
  # new_version_plus: ^0.0.10
  package_info_plus: ^8.1.0
  permission_handler: ^11.3.1
  share_plus: ^10.1.1
  shared_preferences: ^2.3.2
  syncfusion_flutter_pdfviewer: ^27.2.2
  universal_platform: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/google_fonts/
    - assets/images/
    - assets/menu_item/
    - assets/data/parish.json

  fonts:
    - family: FiraSans
      fonts:
        - asset: assets/fonts/google_fonts/FiraSans-Thin.ttf
          weight: 100
        - asset: assets/fonts/google_fonts/FiraSans-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/google_fonts/FiraSans-Light.ttf
          weight: 300
        - asset: assets/fonts/google_fonts/FiraSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/google_fonts/FiraSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/google_fonts/FiraSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/google_fonts/FiraSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/google_fonts/FiraSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/google_fonts/FiraSans-Black.ttf
          weight: 900

    - family: Inter
      fonts:
        - asset: assets/fonts/google_fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/google_fonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/google_fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/google_fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/google_fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/google_fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/google_fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/google_fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/google_fonts/Inter-Black.ttf
          weight: 900

  generate: true